//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ads
    {
        public int id { get; set; }
        public int city_id { get; set; }
        public string region { get; set; }
        public long datetime { get; set; }
        public long update { get; set; }
        public string title { get; set; }
        public long gender { get; set; }
        public long age { get; set; }
        public long weight { get; set; }
        public long height { get; set; }
        public string text { get; set; }
        public string url { get; set; }
        public long state { get; set; }
        public string description { get; set; }
    
        public virtual cities cities { get; set; }
    }
}
